using System;

namespace Contra
{
    /// <summary>
    ///     The base-game file lists embedded in the launcher (static retail content,
    ///     restored from registry-located local installs and never downloaded):
    ///     ZhGeneralsFiles = base Generals 1.04 files the distribution needs,
    ///     ZeroHourFiles = the complete retail Zero Hour 1.04 install.
    ///     Paths are relative to the launcher directory, forwardslash separated.
    /// </summary>
    internal static class BuiltinFileLists
    {
        /// <summary>
        ///     Base Generals content (retail 1.04, minus paths shared with the Zero Hour install).
        /// </summary>
        internal static readonly string[] ZhGeneralsFiles =
        {
            "Audio.big",
            "BrowserEngine.dll",
            "Chinese.big",
            "Data/Movies/CHINA_end.bik",
            "Data/Movies/CHINA_end640.bik",
            "Data/Movies/China01_Final_00s.bik",
            "Data/Movies/China02_Final_00s.bik",
            "Data/Movies/China03_Final_00s.bik",
            "Data/Movies/China04_Final_00s.bik",
            "Data/Movies/China05_Final_00s.bik",
            "Data/Movies/China06_Final_00s.bik",
            "Data/Movies/China07_Final_00s.bik",
            "Data/Movies/GLA01_Final_00s.bik",
            "Data/Movies/GLA02_Final_00s.bik",
            "Data/Movies/GLA03_Final_00s.bik",
            "Data/Movies/GLA04_Final_00s.bik",
            "Data/Movies/GLA05_Final_00s.bik",
            "Data/Movies/GLA06_Final_00s.bik",
            "Data/Movies/GLA07_Final_00s.bik",
            "Data/Movies/GLA08_Final_00s.bik",
            "Data/Movies/GLA_end.bik",
            "Data/Movies/GLA_end640.bik",
            "Data/Movies/Training_Final_00s.bik",
            "Data/Movies/USA01_Final_00s.bik",
            "Data/Movies/USA02_Final_00s.bik",
            "Data/Movies/USA03_Final_00s.bik",
            "Data/Movies/USA04_Final_00s.bik",
            "Data/Movies/USA06_Final_00s.bik",
            "Data/Movies/USA07_Final_00s.bik",
            "Data/Movies/USA08_Final_00s.bik",
            "Data/Movies/USA_end.bik",
            "Data/Movies/USA_end640.bik",
            "INI.big",
            "Patch.big",
            "Speech.big",
            "SpeechChinese.big",
            "Terrain.big",
            "Textures.big",
            "W3D.big",
            "Window.big",
            "audiochinese.big",
            "gensec.big",
            "maps.big",
            "shaders.big",
        };

        /// <summary>
        ///     Complete retail Zero Hour 1.04 install.
        /// </summary>
        internal static readonly string[] ZeroHourFiles =
        {
            "00000000.016",
            "00000000.256",
            "AudioChineseZH.big",
            "AudioZH.big",
            "BINKW32.DLL",
            "ChineseZH.big",
            "Data/Cursors/SCCAttMov.ani",
            "Data/Cursors/SCCAttMov_S.ani",
            "Data/Cursors/SCCAttack_S.ani",
            "Data/Cursors/SCCCashHack.ani",
            "Data/Cursors/SCCEnter.ani",
            "Data/Cursors/SCCEnter_S.ani",
            "Data/Cursors/SCCExit.ani",
            "Data/Cursors/SCCFriendly.ani",
            "Data/Cursors/SCCFriendly_S.ani",
            "Data/Cursors/SCCGuard.ani",
            "Data/Cursors/SCCHeal.ani",
            "Data/Cursors/SCCHostile.ani",
            "Data/Cursors/SCCHostile2.ani",
            "Data/Cursors/SCCHostile3.ani",
            "Data/Cursors/SCCHostile_S.ani",
            "Data/Cursors/SCCKnifeAttack.ani",
            "Data/Cursors/SCCMove_S.ani",
            "Data/Cursors/SCCNoAction.ani",
            "Data/Cursors/SCCNoAction_S.ani",
            "Data/Cursors/SCCNoBomb.ani",
            "Data/Cursors/SCCNoEntry.ani",
            "Data/Cursors/SCCNoEntry_S.ani",
            "Data/Cursors/SCCNoKnife.ani",
            "Data/Cursors/SCCOutrange.ani",
            "Data/Cursors/SCCPlace.ani",
            "Data/Cursors/SCCPlaceBeacon.ani",
            "Data/Cursors/SCCRallyPnt.ani",
            "Data/Cursors/SCCRallyPnt_S.ani",
            "Data/Cursors/SCCRemoteChg.ani",
            "Data/Cursors/SCCRepair.ani",
            "Data/Cursors/SCCResumeC.ani",
            "Data/Cursors/SCCSDIUplink.ani",
            "Data/Cursors/SCCScroll4.ani",
            "Data/Cursors/SCCScroll5.ani",
            "Data/Cursors/SCCScroll6.ani",
            "Data/Cursors/SCCScroll7.ani",
            "Data/Cursors/SCCSelect.ani",
            "Data/Cursors/SCCSell.ani",
            "Data/Cursors/SCCSniper.ani",
            "Data/Cursors/SCCSpyDrone.ani",
            "Data/Cursors/SCCStop.ani",
            "Data/Cursors/SCCTNTAttack.ani",
            "Data/Cursors/SCCTimedChg.ani",
            "Data/Cursors/SCCWaypoint.ani",
            "Data/Cursors/SCCWaypoint_S.ani",
            "Data/Cursors/sccattack.ani",
            "Data/Cursors/sccmove.ani",
            "Data/Cursors/sccpointer.ani",
            "Data/Cursors/sccscroll0.ani",
            "Data/Cursors/sccscroll1.ani",
            "Data/Cursors/sccscroll2.ani",
            "Data/Cursors/sccscroll3.ani",
            "Data/INI/INIZH.big",
            "Data/Movies/GC_Background.bik",
            "Data/Movies/VS_small.bik",
            "Data/Scripts/MultiplayerScripts.scb",
            "Data/Scripts/Scripts.ini",
            "Data/Scripts/SkirmishScripts.scb",
            "Data/WaterPlane/caust00.tga",
            "Data/WaterPlane/caust01.tga",
            "Data/WaterPlane/caust02.tga",
            "Data/WaterPlane/caust03.tga",
            "Data/WaterPlane/caust04.tga",
            "Data/WaterPlane/caust05.tga",
            "Data/WaterPlane/caust06.tga",
            "Data/WaterPlane/caust07.tga",
            "Data/WaterPlane/caust08.tga",
            "Data/WaterPlane/caust09.tga",
            "Data/WaterPlane/caust10.tga",
            "Data/WaterPlane/caust11.tga",
            "Data/WaterPlane/caust12.tga",
            "Data/WaterPlane/caust13.tga",
            "Data/WaterPlane/caust14.tga",
            "Data/WaterPlane/caust15.tga",
            "Data/WaterPlane/caust16.tga",
            "Data/WaterPlane/caust17.tga",
            "Data/WaterPlane/caust18.tga",
            "Data/WaterPlane/caust19.tga",
            "Data/WaterPlane/caust20.tga",
            "Data/WaterPlane/caust21.tga",
            "Data/WaterPlane/caust22.tga",
            "Data/WaterPlane/caust23.tga",
            "Data/WaterPlane/caust24.tga",
            "Data/WaterPlane/caust25.tga",
            "Data/WaterPlane/caust26.tga",
            "Data/WaterPlane/caust27.tga",
            "Data/WaterPlane/caust28.tga",
            "Data/WaterPlane/caust29.tga",
            "Data/WaterPlane/caust30.tga",
            "Data/WaterPlane/caust31.tga",
            "DrvMgt.dll",
            "Generals.dat",
            "Generals.exe",
            "INIZH.big",
            "Install_Final.bmp",
            "MSS/mssa3d.m3d",
            "MSS/mssds3d.m3d",
            "MSS/mssdsp.flt",
            "MSS/mssdx7.m3d",
            "MSS/msseax.m3d",
            "MSS/mssmp3.asi",
            "MSS/mssrsx.m3d",
            "MSS/msssoft.m3d",
            "MSS/mssvoice.asi",
            "MapsZH.big",
            "Music.big",
            "MusicZH.big",
            "P2XDLL.DLL",
            "PatchZH.big",
            "SECDRV.SYS",
            "ShadersZH.big",
            "SpeechChineseZH.big",
            "SpeechZH.big",
            "TerrainZH.big",
            "TexturesZH.big",
            "W3DChineseZH.big",
            "W3DZH.big",
            "WindowZH.big",
            "WorldBuilder.exe",
            "dbghelp.dll",
            "generals.lcf",
            "gensecZH.big",
            "langdata.dat",
            "launcher.bmp",
            "mss32.dll",
            "patchget.dat",
            "patchw32.dll",
        };
    }
}
